# A typical Rakefile

PORT  = 6328
HOSTS = 127.0.1.1

actionset1:
	echo starting actionset1
	remote-cc [optional-flags] -c program.c
		requires program.c program.h allfunctions.h
	remote-cc [optional-flags] -c square.c
		requires square.c allfunctions.h
	remote-cc [optional-flags] -c cube.c
		requires cube.c allfunctions.h

actionset2:
	echo starting actionset2
	remote-cc [optional-flags] -o program program.o square.o cube.o
		requires program.o square.o cube.o